---
apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-apiserver
    image: gcr.io/google_containers/hyperkube:v1.1.7
    command:
    - /hyperkube
    - apiserver
    - --bind-address=0.0.0.0
    - --basic-auth-file=/etc/kubernetes/basicauth.csv
    - --token-auth-file=/etc/kubernetes/tokenauth.csv
    - --etcd_servers=http://127.0.0.1:4001
    - --allow-privileged=true
    - --service-cluster-ip-range=10.0.0.1/24
    - --insecure-bind-address=0.0.0.0
    - --insecure-port=8080
    - --advertise-address=10.111.1.201
    ports:
    - containerPort: 443
      hostPort: 443
      name: https
    - containerPort: 8080
      hostPort: 8080
      name: local
    volumeMounts:
    - mountPath: /etc/kubernetes/ssl
      name: ssl-certs-kubernetes
      readOnly: true
    - mountPath: /etc/ssl/certs
      name: ssl-certs-host
      readOnly: true
    - mountPath: /etc/kubernetes
      name: kubernetes-configfiles
      readOnly: true
  volumes:
  - hostPath:
      path: /etc/kubernetes/ssl
    name: ssl-certs-kubernetes
  - hostPath:
      path: /usr/share/ca-certificates
    name: ssl-certs-host
  - hostPath:
      path: /etc/kubernetes
    name: kubernetes-configfiles
